services:
  tests:
    build: .
    container_name: talon-bot-tests
    command: ["pytest", "-q"]

  talon-bot:
    build: .
    container_name: talon-bot
    restart: unless-stopped
    env_file:
      - .env.server
    volumes:
      - ./state.json:/app/state.json
